(defpackage :starsentocompat
  (:use :cl)
  (:nicknames :star-sento-compat)
  (:export
   #:star-sento-compat-error
   #:unsupported-sento-operation-error
   #:sento-backend-unavailable-error
   #:sento-ask-failure-error
   #:sento-ask-failure-cause
   #:runtime-port
   #:runtime-port-p
   #:make-runtime-port
   #:runtime-spawn
   #:runtime-tell
   #:runtime-ask
   #:runtime-stop
   #:runtime-watch
   #:runtime-unwatch
   #:runtime-link
   #:runtime-resolve
   #:runtime-mailbox-metrics
   #:runtime-shutdown
   #:sento-backend-available-p
   #:sento-remoting-backend-available-p
   #:sento-make-actor-system
   #:sento-enable-remoting
   #:sento-actor-of
   #:sento-ask
   #:sento-reply
   #:sento-make-remote-ref
   #:sento-tell
   #:sento-find-actors
   #:sento-all-actors
   #:sento-actor-live-p
   #:sento-future-complete-p
   #:sento-future-result
   #:sento-stop
   #:sento-disable-remoting
   #:sento-remoting-port
   #:sento-shutdown
   #:make-sento-runtime-port))
