(defpackage :star-document-bus-tests
  (:use :cl :star-document-bus)
  (:export #:run-tests))
(in-package :star-document-bus-tests)
(defun command ()
  (staractorprotocol:make-command-envelope
   :message-id "m1" :message-type "star.documents.put@1"
   :actor "documents" :correlation-id "c1" :idempotency-key "k1"
   :payload nil))
(defun denied (code thunk)
  (handler-case (progn (funcall thunk) (error "Expected rejection ~A" code))
    (bus-error (e) (assert (eq code (bus-error-code e))))))
(defun run-tests ()
  (let ((d (make-delivery-observation (command))))
    (observe-delivery d :broker-confirmed)
    (assert (eq :not-established (delivery-commit-knowledge d)))
    (assert (not (delivery-settle-p d)))
    (observe-delivery d :durably-accepted)
    (assert (delivery-settle-p d))
    (assert (eq :not-established (delivery-commit-knowledge d)))
    (observe-delivery d :disconnected)
    (assert (eq :unknown (delivery-commit-knowledge d)))
    (assert (eq :reconcile-original-key (delivery-retry-action d)))
    (observe-delivery d :committed :receipt '(:outcome-ref "o1"))
    (observe-delivery d :disconnected)
    (assert (eq :committed (delivery-commit-knowledge d)))
    (denied :conflicting-evidence (lambda () (observe-delivery d :not-executed)))
    (denied :conflicting-evidence
            (lambda () (observe-delivery d :committed :receipt '(:outcome-ref "o2"))))
    (denied :conflicting-evidence
            (lambda () (observe-delivery d :committed :receipt '(:outcome-ref "O1"))))
    (observe-delivery d :published)
    (assert (eq :replay-receipt (delivery-retry-action d))))
  (let ((d (make-delivery-observation (command))))
    (denied :commit-required (lambda () (observe-delivery d :published)))
    (denied :receipt-required (lambda () (observe-delivery d :committed)))
    (observe-delivery d :dispatched)
    (observe-delivery d :disconnected)
    (assert (not (delivery-settle-p d)))
    (assert (eq :unknown (delivery-commit-knowledge d))))
  (let ((d (make-delivery-observation (command))))
    (observe-delivery d :not-executed)
    (observe-delivery d :disconnected)
    (assert (eq :not-executed (delivery-commit-knowledge d)))
    (assert (delivery-settle-p d)))
  ;; Durable admission may still produce a durable precondition rejection.
  (let ((d (make-delivery-observation (command))))
    (observe-delivery d :durably-accepted)
    (observe-delivery d :not-executed)
    (assert (eq :not-executed (delivery-commit-knowledge d))))
  (let ((s (make-change-observer :scope "authorized-scope" :credit 2 :retention 3)))
    (assert (eq :deliver (observe-change s "authorized-scope" "e1" "p1" 1 "c1")))
    (assert (eq :duplicate (observe-change s "authorized-scope" "e1" "p1" 1 "c1")))
    (assert (eq :deliver (observe-change s "authorized-scope" "e2" "p2" 1 "c2")))
    (denied :slow-consumer (lambda () (observe-change s "authorized-scope" "e3" "p1" 2 "c3")))
    (denied :checkpoint-order (lambda () (acknowledge-change s "authorized-scope" nil)))
    (assert (null (observer-checkpoint s)))
    (denied :checkpoint-order (lambda () (acknowledge-change s "authorized-scope" "e2")))
    (acknowledge-change s "authorized-scope" "e1")
    (assert (equal "c1" (observer-checkpoint s)))
    (assert (eq :deliver (observe-change s "authorized-scope" "e3" "p1" 2 "c3")))
    (denied :permission-denied (lambda () (acknowledge-change s "other" "e2")))
    (denied :event-conflict (lambda () (observe-change s "authorized-scope" "e1" "p1" 4 "c4")))
    (acknowledge-change s "authorized-scope" "e2")
    (acknowledge-change s "authorized-scope" "e3")
    (assert (eq :deliver (observe-change s "authorized-scope" "e4" "p1" 3 "c4")))
    (denied :history-lost (lambda () (observe-change s "authorized-scope" "e1" "p1" 1 "c1")))
    (close-observer s)
    (denied :closed (lambda () (observe-change s "authorized-scope" "e5" "p1" 4 "c5"))))
  (let ((s (make-change-observer :scope "s" :credit 1 :retention 1)))
    (observe-change s "s" "e1" "p1" 1 "c1")
    (acknowledge-change s "s" "e1")
    (denied :checkpoint-order (lambda () (acknowledge-change s "s" nil)))
    (denied :budget-exceeded (lambda () (observe-change s "s" "e2" "p2" 1 "c2")))
    (assert (eq :deliver (observe-change s "s" "e2" "p1" 3 "c2"))))
  (let* ((d (make-delivery-observation (command)))
         (value (copy-seq "original"))
         (receipt (list :outcome-ref value)))
    (observe-delivery d :committed :receipt receipt)
    (setf (char value 0) #\X)
    (observe-delivery d :committed :receipt '(:outcome-ref "original")))
  ;; Each observation snapshots vector storage; equality must be by exact value.
  (let ((d (make-delivery-observation (command))))
    (observe-delivery d :committed :receipt (list :ids (vector "x" (vector 1))))
    (observe-delivery d :committed :receipt (list :ids (vector "x" (vector 1))))
    (denied :conflicting-evidence
      (lambda () (observe-delivery d :committed
                  :receipt (list :ids (vector "X" (vector 1))))))
    (denied :conflicting-evidence
      (lambda () (observe-delivery d :committed
                  :receipt (list :ids (list "x" (vector 1)))))))
  (let* ((scope (copy-seq "scope"))
         (s (make-change-observer :scope scope :credit 1 :retention 1)))
    (setf (char scope 0) #\X)
    (observe-change s "scope" "e1" "p1" 1 "c1")
    (let ((returned (acknowledge-change s "scope" "e1")))
      (setf (char returned 0) #\X)
      (assert (equal "c1" (observer-checkpoint s)))))
  (denied :invalid-argument (lambda () (make-change-observer :scope "s" :credit 3 :retention 2)))
  (let ((d (make-delivery-observation (command))))
    (observe-delivery d :committed :receipt
      (list :exact (staractorprotocol:make-portable-json-number "1e999999999999999999999")))
    (observe-delivery d :committed :receipt
      (list :exact (staractorprotocol:make-portable-json-number "1e999999999999999999999")))
    (denied :conflicting-evidence
      (lambda () (observe-delivery d :committed :receipt
        (list :exact (staractorprotocol:make-portable-json-number "2e999999999999999999999"))))))
  (format t "Document bus deterministic boundary tests passed.~%")
  t)
