(defpackage :staractorprotocol-service-tests
  (:use :cl :staractorprotocol)
  (:export #:run-tests))
(in-package :staractorprotocol-service-tests)

(defun check (expected actual)
  (unless (equal expected actual)
    (error "Service protocol expected ~S, received ~S" expected actual)))
(defun rejected (thunk)
  (handler-case (progn (funcall thunk) nil)
    (star-actor-protocol-error () t)))
(defun reference (&optional (generation 1))
  (make-star-actor-reference :domain-id "intel" :node-id "local"
    :logical-path "documents" :generation generation :capability-set-hash "caps-1"))
(defun description ()
  (list :actor-ref (reference) :profiles '("star.actor2actor/1" "star.access/1")
        :operations '("star.documents.get@1") :capabilities '("database:read")
        :readiness :ready :max-in-flight 2 :max-message-bytes 1024
        :delivery-classes '(:volatile) :scope '(:database-id "intel" :dataset-id "test")))
(defun command ()
  (make-command-envelope :message-id "request" :message-type "star.documents.get@1"
    :actor "documents" :correlation-id "correlation" :idempotency-key "key"
    :payload '(:scope (:database-id "intel" :dataset-id "test" :document-id "doc"))))
(defun outcome ()
  (make-ack-envelope (command) :message-id "ack" :actor "documents" :status :completed))
(defun admission (desc &rest args)
  (apply #'actor-service-admission-decision desc "star.documents.get@1"
         :authorized-p t :lease-valid-p t :message-bytes 10 args))

(defun run-tests ()
  (let ((definition (list :domain-id "intel" :services (list (description))
                          :max-services 2 :max-in-flight 4)))
    (check t (validate-domain-service-definition definition))
    (setf (getf definition :services) (list (description) (description)))
    (check t (rejected (lambda () (validate-domain-service-definition definition)))))
  (check t (validate-actor-service-description (description)))
  (dolist (key '(:unknown :max-message-bytes))
    (check t (rejected (lambda ()
                        (validate-actor-service-description
                         (append (description) (list key 5)))))))
  (check :unauthorized (actor-service-enrollment-decision (description) nil))
  (check :expired (actor-service-enrollment-decision (description) nil :authorized-p t))
  (check :register (actor-service-enrollment-decision (description) nil
                    :authorized-p t :lease-valid-p t))
  (check :refresh (actor-service-enrollment-decision (description) (reference)
                   :authorized-p t :lease-valid-p t))
  (check :stale-generation (actor-service-enrollment-decision (description) (reference 2)
                            :authorized-p t :lease-valid-p t))
  (check :replace (actor-service-enrollment-decision (description) (reference 0)
                   :authorized-p t :lease-valid-p t))
  (let ((ref (reference)))
    (setf (star-actor-reference-capability-set-hash ref) "other")
    (check :generation-conflict (actor-service-enrollment-decision (description) ref
                                 :authorized-p t :lease-valid-p t)))
  (check :admit (admission (description)))
  (check :overloaded (admission (description) :in-flight 2))
  (check :delivery-unavailable (admission (description) :delivery-class :durable))
  (check :unauthorized (actor-service-admission-decision (description)
                        "star.documents.get@1" :message-bytes 1 :lease-valid-p t))
  (check :operation-unavailable (actor-service-admission-decision (description)
                                 "star.documents.put@1" :message-bytes 1
                                 :authorized-p t :lease-valid-p t))
  (check :message-too-large (actor-service-admission-decision (description)
                             "star.documents.get@1" :message-bytes 1025
                             :authorized-p t :lease-valid-p t))
  (let ((desc (description)))
    (setf (getf desc :readiness) :draining)
    (check :unavailable (admission desc)))
  (check t (validate-correlated-lifecycle-outcome (command) (outcome)))
  (dolist (key '(:correlation-id :causation-id :actor :dataset))
    (let ((bad (outcome)))
      (setf (getf bad key) "wrong")
      (check t (rejected (lambda () (validate-correlated-lifecycle-outcome (command) bad))))))
  (flet ((completion (&rest args)
           (apply #'actor2actor-completion-decision (command) (outcome)
                  (reference) (reference) :expected-attempt 1 :observed-attempt 1 args)))
    (check :accept (completion))
    (check :already-terminal (completion :terminal-p t :cancel-won-p t))
    (check :cancelled (completion :cancel-won-p t))
    (check :deadline-exceeded (completion :deadline-expired-p t)))
  (check :stale-generation
    (actor2actor-completion-decision (command) (outcome) (reference 2) (reference 1)
      :expected-attempt 1 :observed-attempt 1))
  (check :stale-attempt
    (actor2actor-completion-decision (command) (outcome) (reference) (reference)
      :expected-attempt 2 :observed-attempt 1))
  (check t (rejected (lambda ()
    (actor2actor-advance-task
     (make-actor2actor-task :task-id "t" :actor "documents"
                           :correlation-id "correlation" :status :running)
     (make-ack-envelope (command) :message-id "a" :actor "documents" :status :accepted)
     :status :completed))))
  (format t "Service description/admission/correlation/completion protocol tests passed.~%")
  t)
