(defpackage :staractorprotocol
  (:use :cl)
  (:nicknames :star-actor-protocol)
  (:export
   #:star-actor-protocol-error
   #:invalid-star-service-uri-error
   #:invalid-actor-reference-error
   #:invalid-wire-envelope-error
   #:star-service-uri
   #:star-service-uri-p
   #:star-service-uri-domain
   #:star-service-uri-address
   #:star-service-uri-actor-name
   #:make-star-service-uri
   #:parse-star-service-uri
   #:star-service-uri-string
   #:star-service-uri-target-p
   #:ensure-star-service-uri
   #:canonical-star-service-uri-for-actor
   #:star-actor-reference
   #:star-actor-reference-p
   #:star-actor-reference-domain-id
   #:star-actor-reference-logical-path
   #:star-actor-reference-node-id
   #:star-actor-reference-generation
   #:star-actor-reference-protocol-revision
   #:star-actor-reference-capability-set-hash
   #:make-star-actor-reference
   #:star-actor-reference-service-uri
   #:star-actor-reference-same-logical-actor-p
   #:+lifecycle-wire-version+
   #:+ack-message-type+
   #:+error-message-type+
   #:+cancel-message-type+
   #:make-command-envelope
   #:make-event-envelope
   #:make-reply-envelope
   #:make-ack-envelope
   #:make-error-envelope
   #:make-cancel-envelope
   #:validate-lifecycle-envelope
   #:validate-lifecycle-envelope-against-manifest
   #:delivery-outcome
   #:terminal-lifecycle-envelope-p
   #:idempotency-scope-key
   #:lifecycle-message-id
   #:lifecycle-correlation-id
   #:lifecycle-causation-id
   #:cancel-target-message-id
   #:cancel-target-correlation-id
   #:make-wire-envelope
   #:validate-wire-envelope
   #:portable-manifest-message-contract
   #:portable-manifest-type-contract
   #:portable-manifest-document-fields
   #:portable-manifest-actor-contract
   #:portable-actor-accepts-message-p
   #:portable-wire-identifier-string
   #:portable-field-key-string
   #:portable-keyword-plist-p
   #:portable-string-alist-p
   #:portable-payload-entry
   #:validate-portable-wire-fields
   #:validate-portable-wire-value
   #:validate-portable-message-payload))
