(defpackage :staripx
  (:use :cl)
  (:nicknames :star-ipx)
  (:export
   #:ipx-error
   #:invalid-ipx-value-error
   #:ipx-evidence-ref
   #:ipx-evidence-ref-p
   #:make-ipx-evidence-ref
   #:ipx-evidence-ref-source-id
   #:ipx-evidence-ref-record-offset
   #:ipx-evidence-ref-byte-length
   #:ipx-evidence-ref-digest
   #:ipx-http-exchange
   #:ipx-http-exchange-p
   #:make-ipx-http-exchange
   #:ipx-http-exchange-operation-id
   #:ipx-http-exchange-capture-session-id
   #:ipx-http-exchange-exchange-id
   #:ipx-http-exchange-evidence-ref
   #:ipx-http-exchange-timestamp-ms
   #:ipx-http-exchange-method
   #:ipx-http-exchange-scheme
   #:ipx-http-exchange-host
   #:ipx-http-exchange-port
   #:ipx-http-exchange-path
   #:ipx-http-exchange-query-ref
   #:ipx-http-exchange-request-headers-ref
   #:ipx-http-exchange-request-body-ref
   #:ipx-http-exchange-response-status
   #:ipx-http-exchange-response-headers-ref
   #:ipx-http-exchange-response-body-ref
   #:ipx-ingest-ack
   #:ipx-ingest-ack-p
   #:ipx-ingest-ack-status
   #:ipx-ingest-ack-exchange-id
   #:ipx-projection-snapshot
   #:ipx-projection-snapshot-p
   #:ipx-projection-snapshot-exchanges
   #:ipx-actor-system
   #:ipx-actor-system-p
   #:ipx-actor-system-runtime
   #:start-ipx-actor-system
   #:shutdown-ipx-actor-system
   #:submit-ipx-exchange
   #:ipx-system-projections))
