(defpackage :starverification
  (:use :cl)
  (:nicknames :star-verification)
  (:export
   #:star-verification-error
   #:invalid-verification-certificate-error
   #:+verification-certificate-schema+
   #:+verification-class-evidence+
   #:+verification-class-checked-conformance+
   #:+verification-class-lifecycle-verified+
   #:+verification-class-model-checked+
   #:+verification-class-solver-certificate+
   #:+verification-class-theorem-artifact+
   #:+verification-result-valid+
   #:+verification-result-invalid+
   #:+verification-result-inconclusive+
   #:+claim-subject-identity-bound+
   #:+claim-document-schema-conformant+
   #:+claim-document-valid-for-domain+
   #:+claim-document-domain-constraint-satisfied+
   #:+claim-actor-accepts-message+
   #:+claim-actor-emits-message+
   #:+claim-actor-protocol-conformant+
   #:+claim-lifecycle-transition-valid+
   #:+claim-poison-terminal-disposition+
   #:+claim-poison-active-path-nonreturn+
   #:+claim-topology-hard-wait-acyclic+
   #:+claim-topology-protocol-deadlock-free+
   #:+claim-topology-protocol-progress+
   #:verification-certificate-classes
   #:verification-certificate-results
   #:verification-claims
   #:verification-class-p
   #:verification-result-p
   #:verification-claim-p
   #:sha256-digest-p
   #:verification-certificate
   #:verification-certificate-p
   #:make-verification-certificate
   #:verification-certificate-schema
   #:verification-certificate-certificate-id
   #:verification-certificate-class
   #:verification-certificate-claim
   #:verification-certificate-subject-type
   #:verification-certificate-subject-hash
   #:verification-certificate-specification-digest
   #:verification-certificate-plan-digest
   #:verification-certificate-verifier
   #:verification-certificate-verifier-version
   #:verification-certificate-assumptions
   #:verification-certificate-bounds
   #:verification-certificate-evidence
   #:verification-certificate-result
   #:verification-certificate-field-names
   #:verification-certificate-fields
   #:verification-certificate-semantic-identity))
