(in-package :starscrape-tests)
(defun v2-vocabulary ()
  (load-scraper-vocabulary
   (merge-pathnames "../fixtures/star-scrape-core-v2.star" (asdf:system-source-directory :star-scrape))
   :expected-name "org.starscrape/scraper@2"))
(defun example-mapping-plan ()
  '(:input-format :json :max-input-bytes 1048576 :max-rows 100 :max-depth 16
    :scopes ((:name "people" :selector-kind :json-path :selector "$.people"
              :fields ((:name "personName" :selector-kind :json-path :selector "$.name" :kind :value :required t)
                       (:name "orgName" :selector-kind :json-path :selector "$.company" :kind :value :required t))))
    :documents ((:name "person" :scope "people" :document-type "person" :natural-key ("personName")
                 :fields ((:source "personName" :target "fullName")))
                (:name "company" :scope "people" :document-type "org" :natural-key ("orgName")
                 :fields ((:source "orgName" :target "name"))))
    :relations ((:name "employment" :scope "people" :predicate "employed-by"
                 :source-document "person" :destination-document "company"))
    :emit-source t :emit-url nil))
(defun compile-test-mapping (plan)
  (starscrape.schema:compile-mapping-manifest (v2-vocabulary) plan))
(defun test-v2-mapping-contract ()
  (let* ((vocabulary (v2-vocabulary))
         (manifest (compile-test-mapping (example-mapping-plan)))
         (json (scraper-manifest-json manifest)))
    (check (equal vocabulary (v2-vocabulary)) "V2 vocabulary is nondeterministic.")
    (check (= 2 (getf manifest :wire-version)) "Wrong mapping wire version.")
    (check (equal "org.starscrape/mapping-manifest@2" (getf manifest :manifest-schema)) "Wrong mapping envelope.")
    (check (not (getf manifest :policy)) "Offline manifest acquired network policy.")
    (check (string= json (scraper-manifest-json (compile-test-mapping (example-mapping-plan)))) "Nondeterministic mapping manifest.")
    (let ((yason:*parse-object-as* :hash-table) (yason:*parse-json-arrays-as-vectors* t))
      (check (string= json (canonical-json-string (json-nodes-from-decoded (yason:parse json))))
             "V2 canonical JSON round trip changed bytes.")))
  (labels ((reject (mutate description)
             (let ((plan (copy-tree (example-mapping-plan))))
               (funcall mutate plan)
               (check (signals-p 'error (lambda () (compile-test-mapping plan)))
                      "V2 accepted ~A." description))))
    (reject (lambda (p) (setf (getf p :request) '(:password "literal"))) "acquisition in pure mapping")
    (reject (lambda (p) (setf (getf p :max-rows) 10001)) "row budget above bound")
    (reject (lambda (p) (setf (getf p :max-depth) 65)) "depth above bound")
    (reject (lambda (p) (setf (getf p :max-input-bytes) 0)) "zero byte budget")
    (reject (lambda (p) (setf (getf p :scopes) nil)) "empty scopes")
    (reject (lambda (p) (setf (getf p :relations) nil)) "explicit empty relations")
    (reject (lambda (p) (setf (getf (first (getf (first (getf p :scopes)) :fields)) :transform) nil)) "explicit empty transforms")
    (reject (lambda (p) (push (copy-tree (first (getf p :scopes))) (getf p :scopes))) "duplicate scopes")
    (reject (lambda (p) (setf (getf (first (getf p :scopes)) :selector) "$..name")) "recursive JSONPath")
    (reject (lambda (p) (setf (getf (first (getf p :scopes)) :selector) "$.people[*]")) "wildcard JSONPath")
    (reject (lambda (p) (setf (getf (first (getf p :documents)) :document-type) "invented")) "invented dtype")
    (reject (lambda (p) (setf (getf (first (getf p :documents)) :natural-key) '("missing"))) "missing natural key")
    (reject (lambda (p) (setf (getf (first (getf p :documents)) :natural-key) '("personName" "personName"))) "duplicate natural key")
    (reject (lambda (p) (setf (getf (first (getf (first (getf p :documents)) :fields)) :target) "unknown")) "invented canonical field")
    (reject (lambda (p) (setf (getf (first (getf (first (getf p :documents)) :fields)) :target) "id")) "identity overwrite")
    (reject (lambda (p) (setf (getf (first (getf p :relations)) :source-document) "missing")) "dangling emitted-ID binding")
    (reject (lambda (p) (setf (getf (first (getf p :relations)) :source-document) "company")) "wrong predicate endpoint type")
    (reject (lambda (p) (setf (getf (first (getf p :relations)) :predicate) "invented")) "unknown predicate")
    (reject (lambda (p) (setf (getf (first (getf (first (getf p :scopes)) :fields)) :transform) '(:eval))) "executable transform")
    (reject (lambda (p) (setf (getf (first (getf (first (getf p :scopes)) :fields)) :required) nil)) "optional natural key"))
  ;; Both HTML selector dialects preserve the same mapping graph.
  (dolist (dialect '(:css :xpath))
    (let* ((plan (copy-tree (example-mapping-plan)))
           (scope (first (getf plan :scopes))))
      (setf (getf plan :input-format) :html
            (getf scope :selector-kind) dialect
            (getf scope :selector) (if (eq dialect :css) "article.person" "//article"))
      (dolist (field (getf scope :fields))
        (setf (getf field :selector-kind) dialect
              (getf field :selector) (if (eq dialect :css) "span.name" ".//span")
              (getf field :kind) :text
              (getf field :transform) '(:trim)))
      (compile-test-mapping plan)))
  (let* ((plan (copy-tree (example-mapping-plan)))
         (field (first (getf (first (getf plan :scopes)) :fields))))
    (dolist (transform '(:integer :decimal :boolean))
      (setf (getf field :transform) (list transform))
      (compile-test-mapping plan)))
  (check (signals-p 'scraper-schema-error
                   (lambda () (starscrape.schema:compile-mapping-manifest (fixture-vocabulary-manifest) (example-mapping-plan))))
         "V1 vocabulary accepted a v2 mapping plan.")
  (let* ((policy (copy-tree (example-scraper-policy)))
         (vocabulary (v2-vocabulary)))
    (remf policy :extraction) (remf policy :mapping)
    (setf (getf policy :mapping-plan) (example-mapping-plan))
    (check (= 2 (getf (compile-scraper-manifest vocabulary policy) :wire-version)) "V2 acquisition did not compile anonymously.")
    (setf (getf (getf policy :request) :auth-ref) "secret-ref:public-api-optional")
    (compile-scraper-manifest vocabulary policy)
    (dolist (literal '("Bearer secret" "secret-ref:" "secret-ref:a/b" "secret-ref:a?token=secret"))
      (setf (getf (getf policy :request) :auth-ref) literal)
      (check (signals-p 'scraper-policy-error (lambda () (compile-scraper-manifest vocabulary policy)))
             "Credential literal ~S accepted." literal)))
  t)
