(in-package :starlangcompiler)

(defun generate-python-lifecycle-bindings ()
  (with-output-to-string (stream)
    (format stream "from __future__ import annotations~%~%")
    (format stream "from typing import Any, Literal, NotRequired, TypedDict~%~%")
    (format stream "EnvelopeKind = Literal[\"command\", \"event\", \"reply\", \"ack\", \"error\", \"cancel\"]~%")
    (format stream "AckStatus = Literal[\"accepted\", \"completed\", \"rejected\", \"retry\"]~%~%")
    (format stream "class StarEnvelopeBase(TypedDict):~%")
    (format stream "    starVersion: Literal[1]~%")
    (format stream "    kind: EnvelopeKind~%")
    (format stream "    messageId: str~%")
    (format stream "    messageType: str~%")
    (format stream "    actor: str~%")
    (format stream "    correlationId: str~%")
    (format stream "    attempt: int~%")
    (format stream "    payload: dict[str, Any]~%")
    (format stream "    sender: NotRequired[str]~%")
    (format stream "    causationId: NotRequired[str]~%")
    (format stream "    idempotencyKey: NotRequired[str]~%")
    (format stream "    dataset: NotRequired[str]~%")
    (format stream "    replyTo: NotRequired[str]~%")
    (format stream "    sentAt: NotRequired[str]~%")
    (format stream "    deadline: NotRequired[str]~%~%")
    (format stream "class AckPayload(TypedDict):~%")
    (format stream "    status: AckStatus~%")
    (format stream "    forMessageId: str~%")
    (format stream "    reason: NotRequired[str]~%")
    (format stream "    retryAfterMs: NotRequired[int]~%~%")
    (format stream "class ErrorPayload(TypedDict):~%")
    (format stream "    forMessageId: str~%")
    (format stream "    code: str~%")
    (format stream "    message: str~%")
    (format stream "    retryable: bool~%")
    (format stream "    details: NotRequired[Any]~%~%")
    (format stream "class CancelPayload(TypedDict):~%")
    (format stream "    targetMessageId: str~%")
    (format stream "    targetCorrelationId: str~%")
    (format stream "    reason: NotRequired[str]~%")))

(defun generate-typescript-lifecycle-bindings ()
  (with-output-to-string (stream)
    (format stream "export type EnvelopeKind = \"command\" | \"event\" | \"reply\" | \"ack\" | \"error\" | \"cancel\";~%")
    (format stream "export type AckStatus = \"accepted\" | \"completed\" | \"rejected\" | \"retry\";~%~%")
    (format stream "export interface StarEnvelopeBase<TPayload extends object = Record<string, unknown>> {~%")
    (format stream "  starVersion: 1;~%")
    (format stream "  kind: EnvelopeKind;~%")
    (format stream "  messageId: string;~%")
    (format stream "  messageType: string;~%")
    (format stream "  actor: string;~%")
    (format stream "  correlationId: string;~%")
    (format stream "  attempt: number;~%")
    (format stream "  payload: TPayload;~%")
    (format stream "  sender?: string;~%")
    (format stream "  causationId?: string;~%")
    (format stream "  idempotencyKey?: string;~%")
    (format stream "  dataset?: string;~%")
    (format stream "  replyTo?: string;~%")
    (format stream "  sentAt?: string;~%")
    (format stream "  deadline?: string;~%")
    (format stream "}~%~%")
    (format stream "export interface AckPayload {~%")
    (format stream "  status: AckStatus;~%")
    (format stream "  forMessageId: string;~%")
    (format stream "  reason?: string;~%")
    (format stream "  retryAfterMs?: number;~%")
    (format stream "}~%~%")
    (format stream "export interface ErrorPayload {~%")
    (format stream "  forMessageId: string;~%")
    (format stream "  code: string;~%")
    (format stream "  message: string;~%")
    (format stream "  retryable: boolean;~%")
    (format stream "  details?: unknown;~%")
    (format stream "}~%~%")
    (format stream "export interface CancelPayload {~%")
    (format stream "  targetMessageId: string;~%")
    (format stream "  targetCorrelationId: string;~%")
    (format stream "  reason?: string;~%")
    (format stream "}~%~%")
    (format stream "export type AckEnvelope = StarEnvelopeBase<AckPayload> & { kind: \"ack\"; messageType: \"star.protocol/ack@1\" };~%")
    (format stream "export type ErrorEnvelope = StarEnvelopeBase<ErrorPayload> & { kind: \"error\"; messageType: \"star.protocol/error@1\" };~%")
    (format stream "export type CancelEnvelope = StarEnvelopeBase<CancelPayload> & { kind: \"cancel\"; messageType: \"star.protocol/cancel@1\" };~%")))
