(in-package :starlangcompiler)

(defun binding-nim-field-name (name)
  (format nil "`~A`" name))

(defun binding-nim-option-string (value)
  (if value
      (format nil "some(~A)" (binding-string value))
      "none(string)"))

(defun binding-write-nim-metadata (stream metadata)
  (if (null metadata)
      (write-string "newJObject()" stream)
      (progn
        (write-string "%* {" stream)
        (loop for (key . value) in metadata
              for first = t then nil
              do (unless first (write-string ", " stream))
                 (format stream "~A: " (binding-string key))
                 (if (stringp value)
                     (write-string (binding-string value) stream)
                     (princ value stream)))
        (write-char #\} stream))))

(defun binding-generate-nim-object (stream name fields)
  (format stream "type ~A* = object~%" name)
  (if fields
      (dolist (field fields)
        (format stream "  ~A*: ~A~%"
                (binding-nim-field-name (getf field :name))
                (binding-field-type :nim field)))
      (format stream "  discard~%"))
  (terpri stream))

(defun binding-generate-nim (manifest)
  (with-output-to-string (stream)
    (format stream "# Generated by StarLang. Do not edit.~%import std/[json, options, tables]~%~%")
    (format stream "type~%  StarReference* = object~%    schema*: string~%    id*: string~%~%")
    (format stream "  StarActorContract* = object~%    name*: string~%    runtime*: string~%    serviceUri*: Option[string]~%    protocol*: Option[string]~%    endpoint*: Option[string]~%    accepts*: seq[string]~%    produces*: seq[string]~%    capabilities*: seq[string]~%    metadata*: JsonNode~%~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "type ~A* = JsonNode # external: ~A~%"
              (binding-name :nim external)
              external))
    (when (binding-external-contract-names manifest)
      (terpri stream))
    (dolist (contract (getf manifest :types))
      (let ((name (binding-name :nim (getf contract :name))))
        (case (getf contract :kind)
          (:scalar
           (format stream "type ~A* = ~A~%~%"
                   name
                   (binding-type-expression :nim (getf contract :base))))
          (:enum
           (format stream "type ~A* = enum~%" name)
           (loop for value in (getf contract :values)
                 for index from 0
                 do (format stream "  ~AValue~D~A~%"
                            name index (binding-pascal-name value)))
           (terpri stream))
          (:document
           (binding-generate-nim-object
            stream name (binding-document-fields manifest contract))))))
    (dolist (message (getf manifest :messages))
      (binding-generate-nim-object
       stream
       (binding-name :nim (getf message :name))
       (getf message :fields)))
    (dolist (predicate (getf manifest :predicates))
      (format stream "const predicate~A* = (~A, ~A, ~A)~%"
              (binding-pascal-name (getf predicate :name) :local-only nil)
              (binding-string (getf predicate :name))
              (binding-string (getf predicate :source))
              (binding-string (getf predicate :destination))))
    (terpri stream)
    (dolist (actor (getf manifest :actors))
      (format stream "let actor~A* = StarActorContract(name: ~A, runtime: ~A, serviceUri: ~A, protocol: ~A, endpoint: ~A, accepts: "
              (binding-pascal-name (getf actor :name) :local-only nil)
              (binding-string (getf actor :name))
              (binding-string (string-downcase (symbol-name (getf actor :runtime))))
              (binding-nim-option-string (getf actor :service-uri))
              (binding-nim-option-string (getf actor :protocol))
              (binding-nim-option-string (getf actor :endpoint)))
      (binding-write-string-list stream (getf actor :accepts) :prefix "@[" :suffix "]")
      (write-string ", produces: " stream)
      (binding-write-string-list stream (getf actor :produces) :prefix "@[" :suffix "]")
      (write-string ", capabilities: " stream)
      (binding-write-string-list stream (getf actor :capabilities) :prefix "@[" :suffix "]")
      (write-string ", metadata: " stream)
      (binding-write-nim-metadata stream (or (getf actor :metadata) '()))
      (format stream ")~%"))))

(defun binding-go-option-string (value)
  (if value
      (format nil "starString(~A)" (binding-string value))
      "nil"))

(defun binding-go-list (values)
  (if values
      (format nil "[]string{~{~A~^, ~}}" (mapcar #'binding-string values))
      "[]string{}"))

(defun binding-go-metadata (metadata)
  (if metadata
      (format nil "map[string]any{~{~A~^, ~}}"
              (mapcar
               (lambda (entry)
                 (format nil "~A: ~A"
                         (binding-string (car entry))
                         (if (stringp (cdr entry))
                             (binding-string (cdr entry))
                             (princ-to-string (cdr entry)))))
               metadata))
      "map[string]any{}"))

(defun binding-generate-go (manifest)
  (with-output-to-string (stream)
    (format stream "// Code generated by StarLang. DO NOT EDIT.~%package starobjects~%~%")
    (format stream "func starString(value string) *string { return &value }~%~%")
    (format stream "type StarReference struct { Schema string `json:\"schema\"`; ID string `json:\"id\"` }~%")
    (format stream "type StarActorContract struct { Name string; Runtime string; ServiceURI *string; Protocol *string; Endpoint *string; Accepts []string; Produces []string; Capabilities []string; Metadata map[string]any }~%~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "type ~A map[string]any // external: ~A~%"
              (binding-name :go external)
              external))
    (when (binding-external-contract-names manifest)
      (terpri stream))
    (dolist (contract (getf manifest :types))
      (let ((name (binding-name :go (getf contract :name))))
        (case (getf contract :kind)
          (:scalar
           (format stream "type ~A ~A~%~%"
                   name
                   (binding-type-expression :go (getf contract :base))))
          (:enum
           (format stream "type ~A string~%const (~%" name)
           (loop for value in (getf contract :values)
                 for index from 0
                 do (format stream "  ~AValue~D~A ~A = ~A~%"
                            name index (binding-pascal-name value) name
                            (binding-string value)))
           (format stream ")~%~%"))
          (:document
           (format stream "type ~A struct {~%" name)
           (dolist (field (binding-document-fields manifest contract))
             (format stream "  ~A ~A `json:\"~A~:[,omitempty~;~]\"`~%"
                     (binding-pascal-name (getf field :name))
                     (binding-field-type :go field)
                     (getf field :name)
                     (getf field :required)))
           (format stream "}~%~%")))))
    (dolist (message (getf manifest :messages))
      (format stream "type ~A struct {~%"
              (binding-name :go (getf message :name)))
      (dolist (field (getf message :fields))
        (format stream "  ~A ~A `json:\"~A~:[,omitempty~;~]\"`~%"
                (binding-pascal-name (getf field :name))
                (binding-field-type :go field)
                (getf field :name)
                (getf field :required)))
      (format stream "}~%~%"))
    (dolist (predicate (getf manifest :predicates))
      (format stream "var Predicate~A = [3]string{~A, ~A, ~A}~%"
              (binding-pascal-name (getf predicate :name) :local-only nil)
              (binding-string (getf predicate :name))
              (binding-string (getf predicate :source))
              (binding-string (getf predicate :destination))))
    (terpri stream)
    (dolist (actor (getf manifest :actors))
      (format stream "var Actor~A = StarActorContract{Name: ~A, Runtime: ~A, ServiceURI: ~A, Protocol: ~A, Endpoint: ~A, Accepts: ~A, Produces: ~A, Capabilities: ~A, Metadata: ~A}~%"
              (binding-pascal-name (getf actor :name) :local-only nil)
              (binding-string (getf actor :name))
              (binding-string (string-downcase (symbol-name (getf actor :runtime))))
              (binding-go-option-string (getf actor :service-uri))
              (binding-go-option-string (getf actor :protocol))
              (binding-go-option-string (getf actor :endpoint))
              (binding-go-list (getf actor :accepts))
              (binding-go-list (getf actor :produces))
              (binding-go-list (getf actor :capabilities))
              (binding-go-metadata (or (getf actor :metadata) '()))))))

(defparameter +rust-keywords+
  '("as" "break" "const" "continue" "crate" "else" "enum" "extern" "false"
    "fn" "for" "if" "impl" "in" "let" "loop" "match" "mod" "move" "mut"
    "pub" "ref" "return" "self" "Self" "static" "struct" "super" "trait"
    "true" "type" "unsafe" "use" "where" "while" "async" "await" "dyn"))

(defun binding-rust-field-name (name)
  (cond
    ((member name '("self" "Self" "super" "crate") :test #'string=)
     (concatenate 'string "_" name))
    ((member name +rust-keywords+ :test #'string=)
     (concatenate 'string "r#" name))
    (t (binding-snake-name name))))

(defun binding-rust-string-slice (values)
  (format nil "&[~{~A~^, ~}]" (mapcar #'binding-string values)))

(defun binding-rust-metadata (metadata)
  (format nil "&[~{~A~^, ~}]"
          (mapcar
           (lambda (entry)
             (format nil "(~A, ~A)"
                     (binding-string (car entry))
                     (if (stringp (cdr entry))
                         (format nil "StarMetadataValue::Text(~A)"
                                 (binding-string (cdr entry)))
                         (format nil "StarMetadataValue::Integer(~D)"
                                 (cdr entry)))))
           metadata)))

(defun binding-rust-option-string (value)
  (if value
      (format nil "Some(~A)" (binding-string value))
      "None"))

(defun binding-generate-rust (manifest)
  (with-output-to-string (stream)
    (format stream "// Generated by StarLang. Do not edit.~%use serde::{Deserialize, Serialize};~%~%")
    (format stream "#[derive(Clone, Debug, Serialize, Deserialize)]~%pub struct StarReference { pub schema: String, pub id: String }~%~%")
    (format stream "#[derive(Clone, Copy, Debug)]~%pub enum StarMetadataValue { Text(&'static str), Integer(i64) }~%")
    (format stream "#[derive(Clone, Copy, Debug)]~%pub struct StarActorContract { pub name: &'static str, pub runtime: &'static str, pub service_uri: Option<&'static str>, pub protocol: Option<&'static str>, pub endpoint: Option<&'static str>, pub accepts: &'static [&'static str], pub produces: &'static [&'static str], pub capabilities: &'static [&'static str], pub metadata: &'static [(&'static str, StarMetadataValue)] }~%~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "pub type ~A = serde_json::Value; // external: ~A~%"
              (binding-name :rust external)
              external))
    (when (binding-external-contract-names manifest)
      (terpri stream))
    (dolist (contract (getf manifest :types))
      (let ((name (binding-name :rust (getf contract :name))))
        (case (getf contract :kind)
          (:scalar
           (format stream "pub type ~A = ~A;~%~%"
                   name
                   (binding-type-expression :rust (getf contract :base))))
          (:enum
           (format stream "#[derive(Clone, Debug, Serialize, Deserialize)]~%pub enum ~A {~%" name)
           (loop for value in (getf contract :values)
                 for index from 0
                 do (format stream "    #[serde(rename = ~A)] Value~D~A,~%"
                            (binding-string value) index (binding-pascal-name value)))
           (format stream "}~%~%"))
          (:document
           (format stream "#[derive(Clone, Debug, Serialize, Deserialize)]~%pub struct ~A {~%" name)
           (dolist (field (binding-document-fields manifest contract))
             (format stream "    #[serde(rename = ~A)] pub ~A: ~A,~%"
                     (binding-string (getf field :name))
                     (binding-rust-field-name (getf field :name))
                     (binding-field-type :rust field)))
           (format stream "}~%~%")))))
    (dolist (message (getf manifest :messages))
      (format stream "#[derive(Clone, Debug, Serialize, Deserialize)]~%pub struct ~A {~%"
              (binding-name :rust (getf message :name)))
      (dolist (field (getf message :fields))
        (format stream "    #[serde(rename = ~A)] pub ~A: ~A,~%"
                (binding-string (getf field :name))
                (binding-rust-field-name (getf field :name))
                (binding-field-type :rust field)))
      (format stream "}~%~%"))
    (dolist (predicate (getf manifest :predicates))
      (format stream "pub const PREDICATE_~A: (&str, &str, &str) = (~A, ~A, ~A);~%"
              (binding-upper-snake-name (getf predicate :name) :local-only nil)
              (binding-string (getf predicate :name))
              (binding-string (getf predicate :source))
              (binding-string (getf predicate :destination))))
    (terpri stream)
    (dolist (actor (getf manifest :actors))
      (format stream "pub static ACTOR_~A: StarActorContract = StarActorContract { name: ~A, runtime: ~A, service_uri: ~A, protocol: ~A, endpoint: ~A, accepts: ~A, produces: ~A, capabilities: ~A, metadata: ~A };~%"
              (binding-upper-snake-name (getf actor :name) :local-only nil)
              (binding-string (getf actor :name))
              (binding-string (string-downcase (symbol-name (getf actor :runtime))))
              (binding-rust-option-string (getf actor :service-uri))
              (binding-rust-option-string (getf actor :protocol))
              (binding-rust-option-string (getf actor :endpoint))
              (binding-rust-string-slice (getf actor :accepts))
              (binding-rust-string-slice (getf actor :produces))
              (binding-rust-string-slice (getf actor :capabilities))
              (binding-rust-metadata (or (getf actor :metadata) '()))))))
