(in-package :starlangcompiler)

(defun binding-generate-common-lisp (manifest)
  (with-output-to-string (stream)
    (format stream ";;;; Generated by StarLang. Do not edit.~%~%(defstruct star-reference schema id)~%~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "(defstruct ~A) ; external contract ~S~%"
              (binding-name :common-lisp external)
              external))
    (when (binding-external-contract-names manifest)
      (terpri stream))
    (dolist (contract (getf manifest :types))
      (let ((name (binding-name :common-lisp (getf contract :name))))
        (case (getf contract :kind)
          (:scalar
           (format stream "(deftype ~A () '~A)~%~%"
                   name
                   (binding-type-expression :common-lisp (getf contract :base))))
          (:enum
           (format stream "(deftype ~A () '(member ~{~S~^ ~}))~%~%"
                   name
                   (getf contract :values)))
          (:document
           (format stream "(defstruct (~A~@[ (:include ~A)~])~%"
                   name
                   (and (getf contract :extends)
                        (binding-name :common-lisp (getf contract :extends))))
           (dolist (field (getf contract :fields))
             (format stream "  ~A~%" (binding-kebab-name (getf field :name))))
           (format stream ")~%~%")))))
    (dolist (message (getf manifest :messages))
      (format stream "(defstruct ~A~%"
              (binding-name :common-lisp (getf message :name)))
      (dolist (field (getf message :fields))
        (format stream "  ~A~%" (binding-kebab-name (getf field :name))))
      (format stream ")~%~%"))
    (dolist (predicate (getf manifest :predicates))
      (format stream "(defparameter +predicate-~A+ '(:name ~S :source ~S :destination ~S))~%"
              (binding-kebab-name (getf predicate :name) :local-only nil)
              (getf predicate :name)
              (getf predicate :source)
              (getf predicate :destination)))
    (terpri stream)
    (dolist (actor (getf manifest :actors))
      (format stream "(defparameter +actor-~A+ '~S)~%"
              (binding-kebab-name (getf actor :name) :local-only nil)
              actor))))

(defun binding-generate-elisp (manifest)
  (with-output-to-string (stream)
    (format stream ";;; Generated by StarLang. Do not edit. -*- lexical-binding: t; -*-~%~%(require 'cl-lib)~%~%")
    (format stream "(cl-defstruct star-reference schema id)~%~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "(defconst star-external-~A ~S)~%"
              (binding-name :elisp external)
              external))
    (when (binding-external-contract-names manifest)
      (terpri stream))
    (dolist (contract (getf manifest :types))
      (let ((name (binding-name :elisp (getf contract :name))))
        (case (getf contract :kind)
          (:scalar
           (format stream "(defconst star-type-~A '~A)~%"
                   name
                   (binding-type-expression :elisp (getf contract :base))))
          (:enum
           (format stream "(defconst star-enum-~A '~S)~%"
                   name
                   (getf contract :values)))
          (:document
           (format stream "(cl-defstruct star-~A~{ ~A~})~%"
                   name
                   (mapcar (lambda (field)
                             (binding-kebab-name (getf field :name)))
                           (binding-document-fields manifest contract)))))))
    (terpri stream)
    (dolist (message (getf manifest :messages))
      (format stream "(cl-defstruct star-~A~{ ~A~})~%"
              (binding-name :elisp (getf message :name))
              (mapcar (lambda (field)
                        (binding-kebab-name (getf field :name)))
                      (getf message :fields))))
    (dolist (predicate (getf manifest :predicates))
      (format stream "(defconst star-predicate-~A '~S)~%"
              (binding-kebab-name (getf predicate :name) :local-only nil)
              predicate))
    (dolist (actor (getf manifest :actors))
      (format stream "(defconst star-actor-~A '~S)~%"
              (binding-kebab-name (getf actor :name) :local-only nil)
              actor))))

(defun binding-prolog-type (type)
  (cond
    ((and (listp type)
          (= (length type) 2)
          (eq (first type) :list))
     (format nil "list(~A)" (binding-prolog-type (second type))))
    ((and (listp type)
          (= (length type) 2)
          (eq (first type) :optional))
     (format nil "optional(~A)" (binding-prolog-type (second type))))
    ((stringp type)
     (binding-prolog-atom type))
    (t
     (error "Invalid Prolog binding type ~S." type))))

(defun binding-generate-prolog (manifest)
  (with-output-to-string (stream)
    (format stream "%% Generated by StarLang. Do not edit.~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "star_external_contract(~A).~%"
              (binding-prolog-atom external)))
    (dolist (contract (getf manifest :types))
      (case (getf contract :kind)
        (:scalar
         (format stream "star_scalar(~A, ~A).~%"
                 (binding-prolog-atom (getf contract :name))
                 (binding-prolog-atom (getf contract :base))))
        (:enum
         (dolist (value (getf contract :values))
           (format stream "star_enum_value(~A, ~A).~%"
                   (binding-prolog-atom (getf contract :name))
                   (binding-prolog-atom value))))
        (:document
         (format stream "star_document(~A).~%"
                 (binding-prolog-atom (getf contract :name)))
         (when (getf contract :extends)
           (format stream "star_extends(~A, ~A).~%"
                   (binding-prolog-atom (getf contract :name))
                   (binding-prolog-atom (getf contract :extends))))
         (dolist (field (getf contract :fields))
           (format stream "star_field(~A, ~A, ~A, ~A).~%"
                   (binding-prolog-atom (getf contract :name))
                   (binding-prolog-atom (getf field :name))
                   (binding-prolog-type (getf field :type))
                   (if (getf field :required) "required" "optional"))))))
    (dolist (message (getf manifest :messages))
      (format stream "star_message(~A).~%"
              (binding-prolog-atom (getf message :name)))
      (dolist (field (getf message :fields))
        (format stream "star_message_field(~A, ~A, ~A, ~A).~%"
                (binding-prolog-atom (getf message :name))
                (binding-prolog-atom (getf field :name))
                (binding-prolog-type (getf field :type))
                (if (getf field :required) "required" "optional"))))
    (dolist (predicate (getf manifest :predicates))
      (format stream "star_predicate(~A, ~A, ~A).~%"
              (binding-prolog-atom (getf predicate :name))
              (binding-prolog-atom (getf predicate :source))
              (binding-prolog-atom (getf predicate :destination))))
    (dolist (actor (getf manifest :actors))
      (let ((actor-name (binding-prolog-atom (getf actor :name))))
        (format stream "star_actor(~A, ~A).~%"
                actor-name
                (binding-prolog-atom
                 (string-downcase (symbol-name (getf actor :runtime)))))
        (when (getf actor :service-uri)
          (format stream "star_actor_service_uri(~A, ~A).~%"
                  actor-name
                  (binding-prolog-atom (getf actor :service-uri))))
        (when (getf actor :protocol)
          (format stream "star_actor_protocol(~A, ~A).~%"
                  actor-name
                  (binding-prolog-atom (getf actor :protocol))))
        (when (getf actor :endpoint)
          (format stream "star_actor_endpoint(~A, ~A).~%"
                  actor-name
                  (binding-prolog-atom (getf actor :endpoint))))
        (dolist (accepted (getf actor :accepts))
          (format stream "star_actor_accepts(~A, ~A).~%"
                  actor-name
                  (binding-prolog-atom accepted)))
        (dolist (produced (getf actor :produces))
          (format stream "star_actor_produces(~A, ~A).~%"
                  actor-name
                  (binding-prolog-atom produced)))
        (dolist (capability (getf actor :capabilities))
          (format stream "star_actor_capability(~A, ~A).~%"
                  actor-name
                  (binding-prolog-atom capability)))
        (dolist (entry (or (getf actor :metadata) '()))
          (format stream "star_actor_metadata(~A, ~A, ~A).~%"
                  actor-name
                  (binding-prolog-atom (car entry))
                  (if (stringp (cdr entry))
                      (binding-prolog-atom (cdr entry))
                      (princ-to-string (cdr entry)))))))))
