(in-package :starlangcompiler)

(defparameter +java-reserved-words+
  '("abstract" "assert" "boolean" "break" "byte" "case" "catch" "char"
    "class" "const" "continue" "default" "do" "double" "else" "enum"
    "extends" "final" "finally" "float" "for" "goto" "if" "implements"
    "import" "instanceof" "int" "interface" "long" "native" "new" "package"
    "private" "protected" "public" "return" "short" "static" "strictfp"
    "super" "switch" "synchronized" "this" "throw" "throws" "transient"
    "try" "void" "volatile" "while" "record" "sealed" "permits" "yield"))

(defun binding-java-field-name (name)
  (if (member name +java-reserved-words+ :test #'string=)
      (concatenate 'string "_" name)
      name))

(defun binding-java-list (values)
  (if values
      (format nil "List.of(~{~A~^, ~})" (mapcar #'binding-string values))
      "List.of()"))

(defun binding-java-metadata (metadata)
  (if metadata
      (format nil "Map.ofEntries(~{~A~^, ~})"
              (mapcar
               (lambda (entry)
                 (format nil "Map.entry(~A, ~A)"
                         (binding-string (car entry))
                         (if (stringp (cdr entry))
                             (binding-string (cdr entry))
                             (princ-to-string (cdr entry)))))
               metadata))
      "Map.of()"))

(defun binding-generate-java (manifest)
  (with-output-to-string (stream)
    (format stream "// Generated by StarLang. Do not edit.~%import java.util.*;~%~%")
    (format stream "record StarReference(String schema, String id) {}~%")
    (format stream "record StarActorContract(String name, String runtime, String serviceUri, String protocol, String endpoint, List<String> accepts, List<String> produces, List<String> capabilities, Map<String, Object> metadata) {}~%~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "final class ~A { public final Map<String, Object> fields = new LinkedHashMap<>(); } // external: ~A~%"
              (binding-name :java external)
              external))
    (when (binding-external-contract-names manifest)
      (terpri stream))
    (dolist (contract (getf manifest :types))
      (let ((name (binding-name :java (getf contract :name))))
        (case (getf contract :kind)
          (:scalar
           (format stream "record ~A(~A value) {}~%~%"
                   name
                   (binding-type-expression :java (getf contract :base))))
          (:enum
           (format stream "enum ~A { ~{~A~^, ~} }~%~%"
                   name
                   (mapcar #'binding-upper-snake-name (getf contract :values))))
          (:document
           (format stream "class ~A~@[ extends ~A~] {~%"
                   name
                   (and (getf contract :extends)
                        (binding-name :java (getf contract :extends))))
           (dolist (field (getf contract :fields))
             (let* ((wire-name (getf field :name))
                    (java-name (binding-java-field-name wire-name)))
               (format stream "  public ~A ~A;~@[ // wire: ~A~]~%"
                       (binding-type-expression :java (getf field :type))
                       java-name
                       (and (not (string= java-name wire-name)) wire-name))))
           (format stream "}~%~%")))))
    (dolist (message (getf manifest :messages))
      (format stream "class ~A {~%"
              (binding-name :java (getf message :name)))
      (dolist (field (getf message :fields))
        (let* ((wire-name (getf field :name))
               (java-name (binding-java-field-name wire-name)))
          (format stream "  public ~A ~A;~@[ // wire: ~A~]~%"
                  (binding-type-expression :java (getf field :type))
                  java-name
                  (and (not (string= java-name wire-name)) wire-name))))
      (format stream "}~%~%"))
    (format stream "final class StarContracts {~%  private StarContracts() {}~%")
    (dolist (predicate (getf manifest :predicates))
      (format stream "  static final List<String> PREDICATE_~A = List.of(~A, ~A, ~A);~%"
              (binding-upper-snake-name (getf predicate :name))
              (binding-string (getf predicate :name))
              (binding-string (getf predicate :source))
              (binding-string (getf predicate :destination))))
    (dolist (actor (getf manifest :actors))
      (format stream "  static final StarActorContract ACTOR_~A = new StarActorContract(~A, ~A, "
              (binding-upper-snake-name (getf actor :name))
              (binding-string (getf actor :name))
              (binding-string (string-downcase (symbol-name (getf actor :runtime)))))
      (binding-write-nullable-string stream (getf actor :service-uri) "null")
      (write-string ", " stream)
      (binding-write-nullable-string stream (getf actor :protocol) "null")
      (write-string ", " stream)
      (binding-write-nullable-string stream (getf actor :endpoint) "null")
      (format stream ", ~A, ~A, ~A, ~A);~%"
              (binding-java-list (getf actor :accepts))
              (binding-java-list (getf actor :produces))
              (binding-java-list (getf actor :capabilities))
              (binding-java-metadata (or (getf actor :metadata) '()))))
    (format stream "}~%")))

(defun binding-kotlin-field-name (name)
  (format nil "`~A`" name))

(defun binding-kotlin-list (values)
  (if values
      (format nil "listOf(~{~A~^, ~})" (mapcar #'binding-string values))
      "emptyList()"))

(defun binding-kotlin-metadata (metadata)
  (if metadata
      (format nil "mapOf(~{~A~^, ~})"
              (mapcar
               (lambda (entry)
                 (format nil "~A to ~A"
                         (binding-string (car entry))
                         (if (stringp (cdr entry))
                             (binding-string (cdr entry))
                             (princ-to-string (cdr entry)))))
               metadata))
      "emptyMap()"))

(defun binding-generate-kotlin-class (stream target-name fields)
  (if (null fields)
      (format stream "class ~A~%~%" target-name)
      (progn
        (format stream "data class ~A(~%" target-name)
        (loop for field in fields
              for last = (eq field (car (last fields)))
              do (format stream "  val ~A: ~A~:[ = null~;~]~:[,~;~]~%"
                         (binding-kotlin-field-name (getf field :name))
                         (binding-field-type :kotlin field)
                         (getf field :required)
                         last))
        (format stream ")~%~%"))))

(defun binding-generate-kotlin (manifest)
  (with-output-to-string (stream)
    (format stream "// Generated by StarLang. Do not edit.~%data class StarReference(val schema: String, val id: String)~%")
    (format stream "data class StarActorContract(val name: String, val runtime: String, val serviceUri: String?, val protocol: String?, val endpoint: String?, val accepts: List<String>, val produces: List<String>, val capabilities: List<String>, val metadata: Map<String, Any>)~%~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "typealias ~A = Map<String, Any?> // external: ~A~%"
              (binding-name :kotlin external)
              external))
    (when (binding-external-contract-names manifest)
      (terpri stream))
    (dolist (contract (getf manifest :types))
      (let ((name (binding-name :kotlin (getf contract :name))))
        (case (getf contract :kind)
          (:scalar
           (format stream "typealias ~A = ~A~%~%"
                   name
                   (binding-type-expression :kotlin (getf contract :base))))
          (:enum
           (format stream "enum class ~A { ~{~A~^, ~} }~%~%"
                   name
                   (mapcar #'binding-upper-snake-name (getf contract :values))))
          (:document
           (binding-generate-kotlin-class
            stream name (binding-document-fields manifest contract))))))
    (dolist (message (getf manifest :messages))
      (binding-generate-kotlin-class
       stream
       (binding-name :kotlin (getf message :name))
       (getf message :fields)))
    (dolist (predicate (getf manifest :predicates))
      (format stream "val PREDICATE_~A = Triple(~A, ~A, ~A)~%"
              (binding-upper-snake-name (getf predicate :name))
              (binding-string (getf predicate :name))
              (binding-string (getf predicate :source))
              (binding-string (getf predicate :destination))))
    (terpri stream)
    (dolist (actor (getf manifest :actors))
      (format stream "val ACTOR_~A = StarActorContract(~A, ~A, "
              (binding-upper-snake-name (getf actor :name))
              (binding-string (getf actor :name))
              (binding-string (string-downcase (symbol-name (getf actor :runtime)))))
      (binding-write-nullable-string stream (getf actor :service-uri) "null")
      (write-string ", " stream)
      (binding-write-nullable-string stream (getf actor :protocol) "null")
      (write-string ", " stream)
      (binding-write-nullable-string stream (getf actor :endpoint) "null")
      (format stream ", ~A, ~A, ~A, ~A)~%"
              (binding-kotlin-list (getf actor :accepts))
              (binding-kotlin-list (getf actor :produces))
              (binding-kotlin-list (getf actor :capabilities))
              (binding-kotlin-metadata (or (getf actor :metadata) '()))))))
