(in-package :starlangcompiler)

(defun binding-write-python-value (stream value)
  (cond
    ((stringp value) (write-string (binding-string value) stream))
    ((integerp value) (princ value stream))
    ((eq value t) (write-string "True" stream))
    ((null value) (write-string "None" stream))
    (t (error "Unsupported generated Python scalar ~S." value))))

(defun binding-write-python-metadata (stream metadata)
  (write-char #\{ stream)
  (loop for (key . value) in metadata
        for first = t then nil
        do (unless first (write-string ", " stream))
           (format stream "~A: " (binding-string key))
           (binding-write-python-value stream value))
  (write-char #\} stream))

(defun binding-write-typescript-value (stream value)
  (cond
    ((stringp value) (write-string (binding-string value) stream))
    ((integerp value) (princ value stream))
    ((eq value t) (write-string "true" stream))
    ((null value) (write-string "null" stream))
    (t (error "Unsupported generated TypeScript scalar ~S." value))))

(defun binding-write-typescript-metadata (stream metadata)
  (write-char #\{ stream)
  (loop for (key . value) in metadata
        for first = t then nil
        do (unless first (write-string ", " stream))
           (format stream "~A: " (binding-string key))
           (binding-write-typescript-value stream value))
  (write-char #\} stream))

(defun binding-generate-python (manifest)
  (with-output-to-string (stream)
    (format stream "# Generated by StarLang. Do not edit.~%from __future__ import annotations~%~%")
    (format stream "from typing import Any, Literal, NotRequired, Required, TypedDict~%~%")
    (format stream "class StarReference(TypedDict):~%    schema: str~%    id: str~%~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "~A = dict[str, Any]  # external contract ~A~%"
              (binding-name :python external)
              (binding-string external)))
    (when (binding-external-contract-names manifest)
      (terpri stream))
    (dolist (contract (getf manifest :types))
      (let ((name (binding-name :python (getf contract :name))))
        (case (getf contract :kind)
          (:scalar
           (format stream "~A = ~A~%~%"
                   name
                   (binding-type-expression :python (getf contract :base))))
          (:enum
           (format stream "~A = Literal[~{~A~^, ~}]~%~%"
                   name
                   (mapcar #'binding-string (getf contract :values))))
          (:document
           (format stream "~A = TypedDict(~A, {~%" name (binding-string name))
           (dolist (field (binding-document-fields manifest contract))
             (format stream "    ~A: ~A[~A],~%"
                     (binding-string (getf field :name))
                     (if (getf field :required) "Required" "NotRequired")
                     (binding-type-expression :python (getf field :type))))
           (format stream "})~%~%")))))
    (dolist (message (getf manifest :messages))
      (let ((name (binding-name :python (getf message :name))))
        (format stream "~A = TypedDict(~A, {~%" name (binding-string name))
        (dolist (field (getf message :fields))
          (format stream "    ~A: ~A[~A],~%"
                  (binding-string (getf field :name))
                  (if (getf field :required) "Required" "NotRequired")
                  (binding-type-expression :python (getf field :type))))
        (format stream "})~%~%")))
    (format stream "PREDICATES: dict[str, tuple[str, str]] = {~%")
    (dolist (predicate (getf manifest :predicates))
      (format stream "    ~A: (~A, ~A),~%"
              (binding-string (getf predicate :name))
              (binding-string (getf predicate :source))
              (binding-string (getf predicate :destination))))
    (format stream "}~%~%ACTORS: dict[str, dict[str, object]] = {~%")
    (dolist (actor (getf manifest :actors))
      (format stream "    ~A: {\"name\": ~A, \"runtime\": ~A, \"serviceUri\": "
              (binding-string (getf actor :name))
              (binding-string (getf actor :name))
              (binding-string (string-downcase (symbol-name (getf actor :runtime)))))
      (binding-write-nullable-string stream (getf actor :service-uri) "None")
      (write-string ", \"protocol\": " stream)
      (binding-write-nullable-string stream (getf actor :protocol) "None")
      (write-string ", \"endpoint\": " stream)
      (binding-write-nullable-string stream (getf actor :endpoint) "None")
      (write-string ", \"accepts\": " stream)
      (binding-write-string-list stream (getf actor :accepts))
      (write-string ", \"produces\": " stream)
      (binding-write-string-list stream (getf actor :produces))
      (write-string ", \"capabilities\": " stream)
      (binding-write-string-list stream (getf actor :capabilities))
      (write-string ", \"metadata\": " stream)
      (binding-write-python-metadata stream (or (getf actor :metadata) '()))
      (format stream "},~%"))
    (format stream "}~%")))

(defun binding-generate-typescript (manifest)
  (with-output-to-string (stream)
    (format stream "// Generated by StarLang. Do not edit.~%export interface StarReference { schema: string; id: string; }~%~%")
    (dolist (external (binding-external-contract-names manifest))
      (format stream "export interface ~A { [key: string]: unknown } // external: ~A~%"
              (binding-name :typescript external) external))
    (when (binding-external-contract-names manifest)
      (terpri stream))
    (dolist (contract (getf manifest :types))
      (let ((name (binding-name :typescript (getf contract :name))))
        (case (getf contract :kind)
          (:scalar
           (format stream "export type ~A = ~A;~%~%"
                   name
                   (binding-type-expression :typescript (getf contract :base))))
          (:enum
           (format stream "export type ~A = ~{~A~^ | ~};~%~%"
                   name
                   (mapcar #'binding-string (getf contract :values))))
          (:document
           (format stream "export interface ~A~@[ extends ~A~] {~%"
                   name
                   (and (getf contract :extends)
                        (binding-name :typescript (getf contract :extends))))
           (dolist (field (getf contract :fields))
             (format stream "  ~A~:[?~;~]: ~A;~%"
                     (binding-string (getf field :name))
                     (getf field :required)
                     (binding-type-expression :typescript (getf field :type))))
           (format stream "}~%~%")))))
    (dolist (message (getf manifest :messages))
      (format stream "export interface ~A {~%"
              (binding-name :typescript (getf message :name)))
      (dolist (field (getf message :fields))
        (format stream "  ~A~:[?~;~]: ~A;~%"
                (binding-string (getf field :name))
                (getf field :required)
                (binding-type-expression :typescript (getf field :type))))
      (format stream "}~%~%"))
    (format stream "export const predicates = {~%")
    (dolist (predicate (getf manifest :predicates))
      (format stream "  ~A: { source: ~A, destination: ~A },~%"
              (binding-string (getf predicate :name))
              (binding-string (getf predicate :source))
              (binding-string (getf predicate :destination))))
    (format stream "} as const;~%~%export const actors = {~%")
    (dolist (actor (getf manifest :actors))
      (format stream "  ~A: { name: ~A, runtime: ~A, serviceUri: "
              (binding-string (getf actor :name))
              (binding-string (getf actor :name))
              (binding-string (string-downcase (symbol-name (getf actor :runtime)))))
      (binding-write-nullable-string stream (getf actor :service-uri) "null")
      (write-string ", protocol: " stream)
      (binding-write-nullable-string stream (getf actor :protocol) "null")
      (write-string ", endpoint: " stream)
      (binding-write-nullable-string stream (getf actor :endpoint) "null")
      (write-string ", accepts: " stream)
      (binding-write-string-list stream (getf actor :accepts))
      (write-string ", produces: " stream)
      (binding-write-string-list stream (getf actor :produces))
      (write-string ", capabilities: " stream)
      (binding-write-string-list stream (getf actor :capabilities))
      (write-string ", metadata: " stream)
      (binding-write-typescript-metadata stream (or (getf actor :metadata) '()))
      (format stream " },~%"))
    (format stream "} as const;~%")))
