(defpackage :starlangruntime
  (:use :cl)
  (:nicknames :starlang-runtime)
  (:export
   #:actor-runtime-error
   #:actor-definition-error
   #:actor-already-registered-error
   #:actor-not-found-error
   #:actor-stopped-error
   #:actor-stale-reference-error
   #:actor-mailbox-full-error
   #:actor-ask-timeout-error
   #:actor-external-dispatch-required-error
   #:actor-contract-error
   #:runtime-directory-error
   #:runtime-directory-service-not-found-error
   #:runtime-directory-service-unavailable-error
   #:runtime-directory-port
   #:runtime-directory-port-p
   #:make-runtime-directory-port
   #:runtime-directory-snapshot
   #:resolve-star-service-uri
   #:actor-definition
   #:actor-definition-p
   #:actor-definition-name
   #:actor-definition-service-uri
   #:actor-definition-kind
   #:actor-definition-accepts
   #:actor-definition-produces
   #:actor-definition-restart-policy
   #:actor-definition-mailbox-capacity
   #:actor-definition-metadata
   #:make-native-actor-definition
   #:make-external-actor-definition
   #:actor-instance
   #:actor-instance-p
   #:actor-instance-definition
   #:actor-instance-status
   #:actor-instance-data
   #:actor-instance-generation
   #:actor-instance-invocation-count
   #:actor-instance-last-error
   #:actor-running-p
   #:actor-reference
   #:actor-mailbox-depth
   #:runtime
   #:runtime-p
   #:runtime-status
   #:make-runtime
   #:runtime-actor-count
   #:instantiate-actor
   #:register-actor
   #:spawn
   #:create-actor
   #:create-native-actor
   #:create-external-actor
   #:unregister-actor
   #:find-actor
   #:resolve-actor
   #:start-actor
   #:stop-actor
   #:restart-actor
   #:shutdown-runtime
   #:delivery-result
   #:delivery-result-p
   #:delivery-result-status
   #:delivery-result-reference
   #:delivery-result-depth
   #:delivery-result-capacity
   #:dispatch-result
   #:dispatch-result-p
   #:dispatch-result-status
   #:dispatch-result-reference
   #:dispatch-result-correlation-id
   #:dispatch-result-value
   #:dispatch-result-condition
   #:tell
   #:ask
   #:dispatch-next
   #:run-until-idle
   #:invoke-actor

   ;; Deterministic wire dispatcher authority.
   #:wire-dispatcher-error
   #:wire-dispatcher-invalid-actor-error
   #:wire-dispatcher-idempotency-conflict-error
   #:deterministic-dispatcher
   #:deterministic-dispatcher-p
   #:deterministic-dispatcher-manifest
   #:deterministic-dispatcher-queue
   #:deterministic-dispatcher-emitted
   #:deterministic-dispatcher-idempotency
   #:deterministic-dispatcher-handler-count
   #:deterministic-dispatcher-sequence
   #:deterministic-dispatcher-now
   #:make-deterministic-dispatcher
   #:advance-dispatcher-clock
   #:dispatcher-next-message-id
   #:register-dispatch-actor
   #:complete-dispatch
   #:retry-dispatch
   #:fail-dispatch
   #:defer-dispatch
   #:dispatcher-emit
   #:drain-dispatcher-emitted
   #:command-idempotency-record
   #:set-command-idempotency-record
   #:command-idempotency-identity
   #:process-command
   #:submit-dispatch-envelope
   #:run-dispatcher
   #:run-dispatcher-next
   #:redeliver-command
   #:deferred-dispatch-status
   #:finish-deferred-dispatch))
