(defpackage :starlangruntime
  (:use :cl)
  (:nicknames :starlang-runtime)
  (:export
   #:actor-runtime-error
   #:actor-definition-error
   #:actor-already-registered-error
   #:actor-not-found-error
   #:actor-stopped-error
   #:actor-stale-reference-error
   #:actor-mailbox-full-error
   #:actor-ask-timeout-error
   #:actor-external-dispatch-required-error
   #:actor-contract-error
   #:actor-definition
   #:actor-definition-p
   #:actor-definition-name
   #:actor-definition-service-uri
   #:actor-definition-kind
   #:actor-definition-accepts
   #:actor-definition-produces
   #:actor-definition-restart-policy
   #:actor-definition-mailbox-capacity
   #:actor-definition-metadata
   #:make-native-actor-definition
   #:make-external-actor-definition
   #:actor-instance
   #:actor-instance-p
   #:actor-instance-definition
   #:actor-instance-status
   #:actor-instance-data
   #:actor-instance-generation
   #:actor-instance-invocation-count
   #:actor-instance-last-error
   #:actor-running-p
   #:actor-reference
   #:actor-mailbox-depth
   #:runtime
   #:runtime-p
   #:make-runtime
   #:runtime-actor-count
   #:instantiate-actor
   #:register-actor
   #:create-actor
   #:create-native-actor
   #:create-external-actor
   #:unregister-actor
   #:find-actor
   #:resolve-actor
   #:start-actor
   #:stop-actor
   #:restart-actor
   #:delivery-result
   #:delivery-result-p
   #:delivery-result-status
   #:delivery-result-reference
   #:delivery-result-depth
   #:delivery-result-capacity
   #:dispatch-result
   #:dispatch-result-p
   #:dispatch-result-status
   #:dispatch-result-reference
   #:dispatch-result-correlation-id
   #:dispatch-result-value
   #:dispatch-result-condition
   #:tell
   #:ask
   #:dispatch-next
   #:run-until-idle
   #:invoke-actor))